config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', sessions: 'sessions', registrations: 'registrations'}
  root 'welcome#index'
  resources :statistics, only: [:show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/statistic.rb
class Statistic < ApplicationRecord
  belongs_to :statistic_user
end

app/models/statistic_user.rb
class StatisticUser < ApplicationRecord
  has_many :statistics
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook, :twitter, :google_oauth2]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.image = auth.info.image
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.provider = auth.provider
      user.uid = auth.uid
      user.password = Devise.friendly_token[0,20]
    end
  end

  def self.from_twitter_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = "twitter_user#{Random.rand(10000)}@readory.com"
      user.image = auth.info.image
      user.first_name = auth.info.name.split(' ')[0]
      user.last_name = auth.info.name.split(' ')[1]
      user.provider = auth.provider
      user.uid = auth.uid
      user.password = Devise.friendly_token[0,20]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_twitter_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_twitter_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Twitter") if is_navigational_format?
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end


  def failure
    redirect_to root_path
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  respond_to :json
  def create
    @resource = User.new(sign_up_params)
    respond_to do |format|
      if @resource.save
        if @resource.active_for_authentication?
          set_flash_message :notice, :signed_up if is_navigational_format?
          sign_up(resource_name, @resource)
          format.json {render :success => true}
          format.js
        else
          set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
          expire_session_data_after_sign_in!
          format.json {render :success => true}
          format.js
        end
      else
        clean_up_passwords @resource
        format.json {render :success => false, :errors => @resource.errors}
        format.js
      end
    end
  end

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :image)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

  def create
    resource = User.find_for_database_authentication(email: params[:user][:email])
    return invalid_login_attempt unless resource

    if resource.valid_password?(params[:user][:password])
      sign_in :user, resource
      return render nothing: true
    end

    invalid_login_attempt
  end

  protected

    def invalid_login_attempt
      set_flash_message(:alert, :invalid)
      render json: flash[:alert], status: 401
    end

end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController

  def show
    @stat_user = StatisticUser.find(params[:id])
  end

  def create
    user_data = HTTParty.get("https://www.instagram.com/#{params[:nick]}/?__a=1")
    unless user_data["graphql"].nil?
      stat_user = StatisticUser.find_or_create_by(instagram_id: user_data["graphql"]["user"]["id"]) do |user|
        user.name  =  user_data["graphql"]["user"]["full_name"]
        user.nick  =  user_data["graphql"]["user"]["username"]
        user.image =  user_data["graphql"]["user"]["profile_pic_url_hd"]
      end
      statistic = Statistic.new(followers_count:  user_data["graphql"]["user"]["edge_followed_by"]["count"],
                                followings_count: user_data["graphql"]["user"]["edge_follow"]["count"],
                                media_count: user_data["graphql"]["user"]["edge_owner_to_timeline_media"]["count"])
      stat_user.statistics << statistic
      if stat_user.save
        redirect_to statistic_path(stat_user)
      else
        redirect_to root_path
      end
    else
      redirect_to root_path(status: 'not-found')
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @statistic_user = StatisticUser.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def statistics_row user
    template = ''
      user.statistics.each do |stat|
        template = "<tr>"
        template+="<td>#{stat.created_at.strftime("%m-%d-%Y")}</td>"
        template+="<td>#{stat.followers_count}</td>"
        template+="<td>+32</td>"
        template+="<td>#{stat.followings_count}</td>"
        template+="<td>+32</td>"
        template+="<td>#{stat.media_count}</td>"
        template+="<td>+32</td>"
        template +="</tr>"
      end

    template
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstagramScore</title>
    <%= csrf_meta_tags %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <%= stylesheet_link_tag    'application', media: 'all'%>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag :modernizr %>
  </head>

  <body id="page-top">
    <%= yield %>
  </body>
</html>

app/views/statistics/show.html.erb
<div id="wrapper" class="active" style="background-color: #f1f1f1;">
  <div id="sidebar-wrapper">
    <ul id="sidebar_menu" class="sidebar-nav">
      <li class="sidebar-brand">
         <a id="menu-toggle" href="#">
            <div style="position:relative; width:100%; height:100px; padding-top: 20px;">
              <img src="http://graph.facebook.com/v2.6/10208827049106096/picture" style=" border-radius: 100%; margin-left: auto; margin-right: auto; display: block;"><br/>
            </div>
          </a>
      </li>
    </ul>
    <div class="sidebar-center" style="padding-left: 10%;">
      <ul class="sidebar-nav" id="sidebar" style="padding-top: 20px;">
      <li style="padding-top: 20px;"><i class="fa fa-home fa-2x gold-text" aria-hidden="true"></i></li>
      <li style="padding-top: 20px;"><i class="fa fa-cog fa-2x white-text" aria-hidden="true"></i></li>
    </div>
  </div>
  <script type="text/javascript">
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("active");
    });
  </script>
  <div id="page-content-wrapper">

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4 statistic-container">
          <div class="statistic-data">
            <div class="row float-right" style="padding-right: 10px;">?</div>
            <div style="padding: 40px 40px;">
              <span class="gray-text">followers score</span><br />
              <span style="font-size: 60px;" id="followers-score-count" data-followers-score="77">77</span>
              <span style="font-size: 20px;" class="gray-text"> points</span>
            </div>

            <div class="row" style="padding-top: 40px;">
              <div class="col-sm-4">
                <span style="font-size: 13px;" class="purple-text">4321 follower</span>
                <p style="font-size: 12px;" class="gray-text">current total</p>
              </div>
              <div class="col-sm-4">
                <span style="font-size: 13px;" class="purple-text">-2 followers</span>
                <p style="font-size: 12px;" class="gray-text">dialy average</p>
              </div>
              <div class="col-sm-4">
                <span style="font-size: 13px;" class="purple-text">-30 followers</span>
                <p style="font-size: 12px;" class="gray-text">montly average</p>
              </div>
            </div>

          </div>
        </div>
        <div class="col-md-4 statistic-container">
          <div class="statistic-data">
            <div class="row float-right" style="padding-right: 10px;">?</div>
            <div style="padding: 40px 40px;">
              <span class="gray-text">engagement score</span><br />
              <span style="font-size: 60px;"> 77</span>
              <span style="font-size: 20px;" class="gray-text"> points</span>
            </div>

            <div class="row" style="padding-top: 40px;">
              <div class="col-sm-4">
                <span style="font-size: 13px;" class="green-text">4321 follower</span>
                <p style="font-size: 12px;" class="gray-text">current total</p>
              </div>
              <div class="col-sm-4">
                <span style="font-size: 13px;" class="green-text">-2 followers</span>
                <p style="font-size: 12px;" class="gray-text">dialy average</p>
              </div>
              <div class="col-sm-4">
                <span style="font-size: 13px;" class="green-text">-30 followers</span>
                <p style="font-size: 12px;" class="gray-text">montly average</p>
              </div>
            </div>
          </div>
       </div>
        <div class="col-md-4 statistic-container">
          <div class="statistic-data">
            <div class="row float-right" style="padding-right: 10px;">?</div>
            <div style="padding: 40px 40px;">
              <span class="gray-text">activity score</span><br />
              <span style="font-size: 60px;"> 77</span>
              <span style="font-size: 20px;" class="gray-text"> points</span>
            </div>

            <div class="row" style="padding-top: 40px;">
              <div class="col-sm-4">
                <span style="font-size: 13px;" class="blue-text">4321 follower</span>
                <p style="font-size: 12px;" class="gray-text">current total</p>
              </div>
              <div class="col-sm-4">
                <span style="font-size: 13px;" class="blue-text">-2 followers</span>
                <p style="font-size: 12px;" class="gray-text">dialy average</p>
              </div>
              <div class="col-sm-4">
                <span style="font-size: 13px;" class="blue-text">-30 followers</span>
                <p style="font-size: 12px;" class="gray-text">montly average</p>
              </div>
            </div>
          </div>
        </div>
      </div>


       <div class="row">
        <div class="col-md-4 statistic-container">
          <div class="statistic-data">
            <div class="row float-right" style="padding-right: 10px;">?</div>
            <div class="legitimacy-score" style="width: 100%; text-align: center; padding-top: 70px">
              <p style="font-size: 20px;" class="gold-text"> LEGITIMACY SCORE</p>
            </div>
            <div class="legitimacy-score" style="width: 100%; text-align: center; padding-top: 10px">
              <span style="font-size: 60px;"> 77</span>
              <span style="font-size: 20px;" class="gray-text"> /20</span>
            </div>
            <div >
              <div class="ldBar" data-preset="rainbow" data-value="77"></div>
            </div>
          </div>
        </div>
        <div class="col-md-8 statistic-container">
          <div class="statistic-data">
            <div style="padding: 20px 60px;">
            <table style=" text-align:center; vertical-align:middle; width: 100%;">
              <thead>
                <th class="gold-text">Date</th>
                <th class="gold-text">Followers</th>
                <th class="gold-text"></th>
                <th class="gold-text">Following</th>
                <th class="gold-text"></th>
                <th class="gold-text">Media</th>
                <th class="gold-text"></th>
              </thead>
              <tbody>
                <tr style="height: 20px;"><td></td></tr>
                <%= raw statistics_row @stat_user %>
              </tbody>
            </table>
            </div>
          </div>
       </div>
      </div>



       <div class="row">
        <div class="col-md-6 statistic-container">
          <div class="statistic-data last-three ad-column">
          <h6>Advertisement block</h6>

          </div>
        </div>
        <div class="col-md-3 statistic-container">
          <div class="statistic-data last-three">
            <div class="user-info">
              <div>
                <b>@<%= @stat_user.nick %></b>
              </div>
              <table style="font-size: 13px;">
                <tr style="height: 20px;"><td></td></tr>
                <tr>
                  <td><b>Full Name</b></td>
                  <td><%= @stat_user.name %></td>
                </tr>
                <tr>
                  <td><b>Id</b></td>
                  <td><%= @stat_user.instagram_id %></td>
                </tr>
                <tr>
                  <td><b>Following</b></td>
                  <td><%= @stat_user.statistics.last.followings_count %></td>
                </tr>
                <tr>
                  <td><b>Followers</b></td>
                  <td><%= @stat_user.statistics.last.followers_count %></td>
                </tr>
                <tr>
                  <td><b>Uploaded</b></td>
                  <td><%= @stat_user.statistics.last.media_count %></td>
                </tr>
              </table>
            </div>
          </div>
       </div>
        <div class="col-md-3 statistic-container">
          <div class="statistic-data last-three">
            <img class="user-placeholder" src="<%= @stat_user.image %>"/>
          </div>
        </div>
      </div>

    </div>














  </div>

</div>

app/views/welcome/index.html.erb
<nav class="navbar navbar-expand-lg" style="background-color: #000000;">
  <h1>LOGO</h1>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

    </ul>
    <ul class="navbar-nav my-2 my-lg-0">
      <li class="nav-item">
        <a class="nav-link cd-signin" href="#0">REGISTER/LOGIN</a>
      </li>
    </ul>
  </div>
</nav>

<!-- Header -->
<header class="masthead text-white text-center" style="background-color: #000000; font-size: 10px;">
  <div class="container" style="border: 1px solid white; height: 220px; width: 770px;">
    <h1 class="text-uppercase mb-0">CHECK THE LEGITIMACY</h1><br />
    <h1 class="text-uppercase mb-0" style="color: #f0ac1d;">OF INSTAGRAM ACCOUNTS</h1>
  </div>

  <ul class="nav justify-content-center">
    <li class="nav-item">
      <form class="form-inline" action="<%= statistics_path %>" method="post" style="padding-top: 30px;">
      <%= form_for statistics_path, class: "form-inline", method: :post do %>
        <input type="text" name="nick" style="width: 650px; height: 30px;">
        <input type="submit" value="Submit" style="height: 30px; width: 100px; background-color: #f1ad1e;">
      <% end %>
    </li>
  </ul>

</header>

<!-- Portfolio Grid Section -->
<section class="portfolio" id="portfolio">
  <div class="container">
    <p class="text-center text-uppercase text-secondary mb-0"><b>Check how legit an instagram account is </b></p>
    <br />
    <p class="text-center text-secondary mb-0">
      ... gives all registered users the possibility to use our advanced technology, to provide you insights of the likelihood if an Instagram account is legit or not.<br />
      Whether you are a 5-star resort, a well-known restaurant or a beginning brand, we offer a independent advice if an account is suitable for influencer<br /> marketing. As well to check-up suspicious friends with a sudden skyrocketing instagram account.
    </p>
  </div>
  <div class="row">
    <div class="col-md-3">
      <div class="col-md-12 text-center" style="background-color: #333333;">
        <h3 class="text-uppercase mb-0" style="color: #ffffff;">100%</h3>
        <h3 class="text-uppercase mb-0" style="color: #f0ac1d;">free</h3>
      </div>
    </div>
    <div class="col-md-3">
      <div class="col-md-12 text-center" style="background-color: #333333;">
        <h3 class="text-uppercase mb-0" style="color: #ffffff;">advanced</h3>
        <h3 class="text-uppercase mb-0" style="color: #f0ac1d;">analytics</h3>
      </div>
    </div>
    <div class="col-md-3">
      <div class="col-md-12 text-center" style="background-color: #333333;">
        <h3 class="text-uppercase mb-0" style="color: #ffffff;">easy</h3>
        <h3 class="text-uppercase mb-0" style="color: #f0ac1d;">to use</h3>
      </div>
    </div>
    <div class="col-md-3">
      <div class="col-md-12 text-center" style="background-color: #333333;">
        <h3 class="text-uppercase mb-0" style="color: #ffffff;">simplified</h3>
        <h3 class="text-uppercase mb-0" style="color: #f0ac1d;">scoring</h3>
      </div>
    </div>

  </div>
</section>

<!-- About Section -->
<section class="text-white mb-0" id="about" style="background-color: #000000;">
  <div class="container">
    <h4 class="text-center text-uppercase text-white">get your results,</h4>
    <h4 class="text-center text-uppercase" style="color: #f0ac1d;">register now for free</h4>
    <hr style="background-color: #fff; width: 10%;">
    <div class="text-center mt-4">
      <a class="btn btn-xl btn-outline-light" href="#">
        REGISTER NOW
      </a>
    </div>
  </div>
</section>

<!-- Contact Section -->
<section id="contact">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-centered">

      </div>
      <div class="col-md-3 col-centered">
        <div class="row" style="background-color: #333333; margin-bottom: 20px; height: 50px; font-size: 20px;">
          <b>
          <span style="color: #f0ac1d;"> Usefull </span>
          <span style="color: #ffffff;"> Links </span>
          </b>
        </div>
        <ul class="list-group" style="list-style-type: none;">
          <li>Press</li>
          <li>Blog</li>
          <li>About Us</li>
          <li>Contact</li>
        </ul>
      </div>
      <div class="col-md-3 col-centered">
        <div class="row" style="background-color: #333333; margin-bottom: 20px; height: 50px; font-size: 20px;">
          <b>
          <span style="color: #f0ac1d;"> Follow </span>
          <span style="color: #ffffff;"> Us </span>
          </b>
        </div>
        <ul class="list-inline">
           <li class="list-inline-item"><a style="background-color: #f0ac1d;" class="btn btn-sq-lg social-icon text-xs-center" target="_blank" href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
           <li class="list-inline-item"><a style="background-color: #f0ac1d;" class="btn btn-sq-lg social-icon text-xs-center" target="_blank" href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
           <li class="list-inline-item"><a style="background-color: #f0ac1d;" class="btn btn-sq-lg social-icon text-xs-center" target="_blank" href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
           <li class="list-inline-item"><a style="background-color: #f0ac1d;" class="btn btn-sq-lg social-icon text-xs-center" target="_blank" href="#"><i class="fa fa-rss" aria-hidden="true"></i></a></li>
        </ul>
      </div>
    </div>
  </div>
</section>

<!-- Footer -->
<footer class="text-center" style="background-color: #333333;">
  <div class="container">
    <div class="row">
      Get Started Today
    </div>
  </div>
</footer>

<div class="py-4 text-center text-white">
  <div class="container">
    <small>Copyright &copy; Your Website 2018</small>
  </div>
</div>

<!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
<div class="scroll-to-top d-lg-none position-fixed ">
  <a class="js-scroll-trigger d-block text-center text-white rounded" href="#page-top">
    <i class="fa fa-chevron-up"></i>
  </a>
</div>


<div class="cd-user-modal"> <!-- this is the entire modal form, including the background -->
  <div class="cd-user-modal-container"> <!-- this is the container wrapper -->
    <ul class="cd-switcher">
      <li><a href="#0">Sign in</a></li>
      <li><a href="#0">New account</a></li>
    </ul>

    <div id="cd-login"> <!-- log in form -->
      <%= form_for(resource, :as => resource_name,
                   :url => session_path(resource_name) ,
                   :html => {:id => "sign_in_user", class: 'cd-form'},
                   :format => :json,
                   :remote => true ) do |f| %>
        <p class="fieldset">
          <label class="image-replace cd-email" for="signin-email">E-mail</label>
          <%= f.email_field :email, placeholder: 'E-mail', class: 'full-width has-padding has-border' %>
          <span class="cd-error-message">Error message here!</span>
        </p>

        <p class="fieldset">
          <label class="image-replace cd-password" for="signin-password">Password</label>
           <%= f.password_field :password, placeholder: "password", class: "full-width has-padding has-border" %>
          <a href="#0" class="hide-password">Hide</a>
          <span class="cd-error-message">Error message here!</span>
        </p>

        <p class="fieldset">
          <input type="checkbox" id="remember-me" checked>
          <label for="remember-me">Remember me</label>
        </p>

        <p class="fieldset">
          <%= f.submit "Sign in", class: 'full-width' %>
        </p>
      <% end %>

      <p class="cd-form-bottom-message"><a href="#0">Forgot your password?</a></p>
      <!-- <a href="#0" class="cd-close-form">Close</a> -->
    </div> <!-- cd-login -->

    <div id="cd-signup"> <!-- sign up form -->
      <%= form_for(resource, :as => resource_name,
                   :url => registration_path(resource_name) ,
                   :html => {:id => "sign_up_user", class: 'cd-form'},
                   :format => :js,
                   :remote => true ) do |f| %>
        <p class="fieldset">
          <label class="image-replace cd-email" for="signup-email">E-mail</label>
          <%= f.email_field :email, placeholder: 'E-mail', class: 'full-width has-padding has-border' %>
          <span class="cd-error-message">Error message here!</span>
        </p>

        <p class="fieldset">
          <label class="image-replace cd-password" for="signup-password">Password</label>
          <%= f.password_field :password, placeholder: "password", class: "full-width has-padding has-border" %>
          <a href="#0" class="hide-password">Hide</a>
          <span class="cd-error-message">Error message here!</span>
        </p>

        <p class="fieldset">
          <label class="image-replace cd-password" for="signup-password">Password</label>
          <%= f.password_field :password_confirmation, placeholder: "password confirmation", id: 'register_user_password_confirmation', class: "full-width has-padding has-border" %>
          <a href="#0" class="hide-password">Hide</a>
          <span class="cd-error-message">Error message here!</span>
        </p>

        <p class="fieldset">
          <input type="checkbox" id="accept-terms">
          <label for="accept-terms">I agree to the <a href="#0">Terms</a></label>
        </p>

        <p class="fieldset">
          <%= f.submit "Sign up", class: 'full-width' %>
        </p>
      <% end %>

      <!-- <a href="#0" class="cd-close-form">Close</a> -->
    </div> <!-- cd-signup -->

    <div id="cd-reset-password"> <!-- reset password form -->
      <p class="cd-form-message">Lost your password? Please enter your email address. You will receive a link to create a new password.</p>

      <form class="cd-form">
        <p class="fieldset">
          <label class="image-replace cd-email" for="reset-email">E-mail</label>
          <input class="full-width has-padding has-border" id="reset-email" type="email" placeholder="E-mail">
          <span class="cd-error-message">Error message here!</span>
        </p>

        <p class="fieldset">
          <input class="full-width has-padding" type="submit" value="Reset password">
        </p>
      </form>

      <p class="cd-form-bottom-message"><a href="#0">Back to log-in</a></p>
    </div> <!-- cd-reset-password -->
    <a href="#0" class="cd-close-form">Close</a>
  </div> <!-- cd-user-modal-container -->
</div> <!-- cd-user-modal -->